# Generated by Django 5.1.5 on 2025-02-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='plan',
            field=models.CharField(default='free', max_length=10),
        ),
        migrations.AddField(
            model_name='subscribers',
            name='qr_code_count',
            field=models.IntegerField(default=0),
        ),
    ]
