# Generated by Django 3.2.19 on 2025-02-22 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_subscribers_plan_subscribers_qr_code_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr_code',
            name='subscriber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.subscribers'),
        ),
    ]
