# Generated by Django 3.2.19 on 2025-02-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_qr_code_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qr_code',
            name='subscriber',
        ),
    ]
