# Generated by Django 3.2.19 on 2025-02-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_qr_code_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='qr_code_limit',
            field=models.IntegerField(default=10),
        ),
    ]
