# Generated by Django 3.2.19 on 2025-02-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_subscribers_qr_code_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
