# Generated by Django 3.2.19 on 2025-02-27 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_subscribers_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr_code',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qr_code',
            name='custom_style',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='qr_code',
            name='data_create',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='qr_code',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qr_code',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='qr_code',
            name='shape',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qr_code',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
