# Generated by Django 3.2.19 on 2025-03-02 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_auto_20250227_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr_code',
            name='expiry_date',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qr_code',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
