# Generated by Django 3.2.19 on 2025-03-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20250302_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr_code',
            name='created_plan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
