# Generated by Django 3.2.19 on 2025-03-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_qr_code_created_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qr_code',
            name='created_plan',
        ),
        migrations.AlterField(
            model_name='qr_code',
            name='expiry_date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
