# Generated by Django 3.2.19 on 2025-03-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20250302_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr_code',
            name='plan',
            field=models.CharField(default='free', max_length=10),
        ),
    ]
