# Generated by Django 3.2.19 on 2025-03-02 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_qr_code_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qr_code',
            name='plan',
        ),
    ]
