# Generated by Django 3.2.19 on 2025-03-02 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import time


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0012_remove_qr_code_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr_code',
            name='plan_created',
            field=models.CharField(default='free', max_length=50),
        ),
        migrations.AlterField(
            model_name='qr_code',
            name='custom_style',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AlterField(
            model_name='qr_code',
            name='data_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='qr_code',
            name='expiry_date',
            field=models.FloatField(default=time.time),
        ),
        migrations.AlterField(
            model_name='qr_code',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='qr_code',
            name='link',
            field=models.URLField(default='http://example.com', max_length=2000),
        ),
        migrations.AlterField(
            model_name='qr_code',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='qr_code',
            name='shape',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='qr_code',
            name='size',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='qr_code',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
