# Generated by Django 3.2.19 on 2025-03-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20250302_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr_code',
            name='link',
            field=models.URLField(default='http://127.0.0.1:8000/', max_length=2000),
        ),
    ]
