# Generated by Django 3.2.19 on 2025-03-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_qr_code_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr_code',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/%Y/%m/%d/'),
        ),
    ]
