# Generated by Django 3.2.19 on 2025-03-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_qr_code_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr_code',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
